POST http://{{host}}/api/merk
Content-Type: application/json

{
  "text": "Jetzt noch ne gaaaanz andere Notiz"
}

###

DELETE http://{{host}}/api/merk
Content-Type: application/json

{
  "id": "{{current-merk}}"
}

###

GET http://{{host}}/api/merk
Accept: application/json

###

GET http://{{host}}/api/merk/{{current-merk}}
Accept: application/json

###

PUT http://{{host}}/api/merk/{{current-merk}}
Content-Type: application/json

{
  "content": "Neuer Text"
}

###